/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_jterminal_instance_AbstractNativeTerminal */

#ifndef _Included_net_jterminal_instance_AbstractNativeTerminal
#define _Included_net_jterminal_instance_AbstractNativeTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _create
 * Signature: (BI)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1create
  (JNIEnv *, jobject, jbyte, jint);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _set
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1set
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _isActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1isActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1shutdown
  (JNIEnv *, jobject);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _resetAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1resetAll
  (JNIEnv *, jobject);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _setBuffer
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1setBuffer
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    isAlive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_jterminal_instance_AbstractNativeTerminal_isAlive
  (JNIEnv *, jobject);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _construct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1construct
  (JNIEnv *, jobject);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _destruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1destruct
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _setFlags
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1setFlags
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _getFlags
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1getFlags
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _update
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1update
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _reset
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1reset
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _beep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1beep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _createInputStream
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1createInputStream
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _disposeInputStream
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1disposeInputStream
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _getWindowPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1getWindowPointer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _setTitle
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1setTitle
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _getTitle
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1getTitle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _setDim
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1setDim
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _getDim
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1getDim
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _setCursor
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1setCursor
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _requestCursor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1requestCursor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _setCursorFlags
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1setCursorFlags
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     net_jterminal_instance_AbstractNativeTerminal
 * Method:    _getCursorFlags
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_jterminal_instance_AbstractNativeTerminal__1getCursorFlags
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
