/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_jterminal_input_NativeTerminalInput */

#ifndef _Included_net_jterminal_input_NativeTerminalInput
#define _Included_net_jterminal_input_NativeTerminalInput
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _createInputStream
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_jterminal_input_NativeTerminalInput__1createInputStream
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _disposeInputStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_input_NativeTerminalInput__1disposeInputStream
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _read
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_jterminal_input_NativeTerminalInput__1read__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _avail
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_jterminal_input_NativeTerminalInput__1avail
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _peek
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_net_jterminal_input_NativeTerminalInput__1peek
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _read
 * Signature: (J[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_net_jterminal_input_NativeTerminalInput__1read__J_3BIIJ
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong);

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _peekInput
 * Signature: (JLnet/jterminal/util/Ref;)I
 */
JNIEXPORT jint JNICALL Java_net_jterminal_input_NativeTerminalInput__1peekInput
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _readInput
 * Signature: (JJ)Lnet/jterminal/input/InputEvent;
 */
JNIEXPORT jobject JNICALL Java_net_jterminal_input_NativeTerminalInput__1readInput
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_jterminal_input_NativeTerminalInput
 * Method:    _reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_input_NativeTerminalInput__1reset
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
