#ifdef TERMINAL_WIN
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_jterminal_windows_WindowsTerminalImpl */

#ifndef _Included_net_jterminal_windows_WindowsTerminalImpl
#define _Included_net_jterminal_windows_WindowsTerminalImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_jterminal_windows_WindowsTerminalImpl
 * Method:    setWindowVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_windows_WindowsTerminalImpl_setWindowVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_jterminal_windows_WindowsTerminalImpl
 * Method:    isWindowVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_jterminal_windows_WindowsTerminalImpl_isWindowVisible
  (JNIEnv *, jobject);

/*
 * Class:     net_jterminal_windows_WindowsTerminalImpl
 * Method:    setGraphicUpdate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_windows_WindowsTerminalImpl_setGraphicUpdate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_jterminal_windows_WindowsTerminalImpl
 * Method:    moveWindow
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_net_jterminal_windows_WindowsTerminalImpl_moveWindow
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     net_jterminal_windows_WindowsTerminalImpl
 * Method:    getWindowPosDim
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_net_jterminal_windows_WindowsTerminalImpl_getWindowPosDim
  (JNIEnv *, jobject);

/*
 * Class:     net_jterminal_windows_WindowsTerminalImpl
 * Method:    isWindowOnFocus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_jterminal_windows_WindowsTerminalImpl_isWindowOnFocus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
#endif